baseURL = "/"
languageCode = "en-us"
title = "Scrapex Lite"
themesDir = "themes"
theme = "dot"
paginate = 9
publishDir = "build"

[params]
siteURL = "https://distill.io/"
appURL = "https://app.distill.io/login"
thumbnailURL = "https://distill.io"
description = "Find answer to most FAQs in our help documentation. If you need further help email us at support@distill.io"

primaryColor = "#0086ff"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

# breadcrumbs
    [Languages.en.params.breadcrumbs]
      home = "Home"
      blog = "Blog"
      docs = "Docs"
# footer social icon
    [[Languages.en.socialIcon]]
      icon = "ti-twitter-alt"
      linkURL = "https://twitter.com/scrapex_ai"

    [[Languages.en.socialIcon]]
      icon = "ti-facebook"
      linkURL = "https://www.facebook.com/Official.ScrapeX/"
      
    [[Languages.en.socialIcon]]
      icon = "ti-linkedin"
      linkURL = "https://www.linkedin.com/company/scrapex-ai/"
